### ISSUE TITLE
Add "Contact" section

### ISSUE THREAD

**Issue by omn0mn0m** [GWIC/dub.works#6]
Fairly simple. Make a section on the landing page that has the following text:

> Want to join the community? Let us know what excites you at volunteer@dub.works.
> 
> Ideas? Suggestions? Email us at contact@dub.works.
> 
> Want to host an event in our space? Have a project to share?

Also include a button to "Get Involved" that links to [this form](https://docs.google.com/forms/d/e/1FAIpQLSfjDOKxayv90cJ7zg4bJewWdwmdRSs_roDzS5NUCvA_bRj8Nw/viewform). The form should later be internalised on the server.

**Comment by rebeccc** [comment]
Needs testing

**Comment by omn0mn0m** [comment]
Tested and confirmed working. Messages are saved in Enquiries section
